-- Auto-generated by qedgen asm2lean from asm-slippage.s
-- DO NOT EDIT — regenerate with: qedgen asm2lean --input asm-slippage.s
-- source-hash: sha256:d10a405b4edfe2327aa6c6c584e285dcb40040e66cd039f0ba40fda3e1e1039f

import SVM.SBPF

namespace SlippageProg

open SVM.SBPF

/-! ## .equ constants -/

abbrev TOKEN_ACCOUNT_BALANCE : Int := 0xa0
abbrev MINIMUM_BALANCE : Int := 0x2918

/-! ## effectiveAddr lemmas -/

section EffectiveAddr

open SVM.SBPF.Memory

@[simp] theorem ea_MINIMUM_BALANCE (b : Nat) : effectiveAddr b MINIMUM_BALANCE = b + 10520 := by
  unfold effectiveAddr MINIMUM_BALANCE; omega

@[simp] theorem ea_TOKEN_ACCOUNT_BALANCE (b : Nat) : effectiveAddr b TOKEN_ACCOUNT_BALANCE = b + 160 := by
  unfold effectiveAddr TOKEN_ACCOUNT_BALANCE; omega

end EffectiveAddr

/-! ## Program -/

@[simp] def prog : Program := #[
  .ldx .dword .r3 .r1 MINIMUM_BALANCE,             -- 0: entrypoint
  .ldx .dword .r4 .r1 TOKEN_ACCOUNT_BALANCE,       -- 1
  .jge .r3 (.reg .r4) 4,                           -- 2
  .exit,                                           -- 3
  .lddw .r1 0 /- undefined: e -/,                  -- 4: end
  .lddw .r2 17,                                    -- 5
  .call .sol_log_,                                 -- 6
  .lddw .r0 1,                                     -- 7
  .exit                                             -- 8
]

@[simp] def progAt : Nat → Option SVM.SBPF.Insn
  | 0 => some (.ldx .dword .r3 .r1 MINIMUM_BALANCE)
  | 1 => some (.ldx .dword .r4 .r1 TOKEN_ACCOUNT_BALANCE)
  | 2 => some (.jge .r3 (.reg .r4) 4)
  | 3 => some (.exit)
  | 4 => some (.lddw .r1 0 /- undefined: e -/)
  | 5 => some (.lddw .r2 17)
  | 6 => some (.call .sol_log_)
  | 7 => some (.lddw .r0 1)
  | 8 => some (.exit)
  | _ => none

/-! ## Instruction fetch cache -/

@[simp] theorem insn_0 : progAt 0 = some (.ldx .dword .r3 .r1 MINIMUM_BALANCE) := by native_decide
@[simp] theorem insn_1 : progAt 1 = some (.ldx .dword .r4 .r1 TOKEN_ACCOUNT_BALANCE) := by native_decide
@[simp] theorem insn_2 : progAt 2 = some (.jge .r3 (.reg .r4) 4) := by native_decide
@[simp] theorem insn_3 : progAt 3 = some (.exit) := by native_decide
@[simp] theorem insn_4 : progAt 4 = some (.lddw .r1 0 /- undefined: e -/) := by native_decide
@[simp] theorem insn_5 : progAt 5 = some (.lddw .r2 17) := by native_decide
@[simp] theorem insn_6 : progAt 6 = some (.call .sol_log_) := by native_decide
@[simp] theorem insn_7 : progAt 7 = some (.lddw .r0 1) := by native_decide
@[simp] theorem insn_8 : progAt 8 = some (.exit) := by native_decide

end SlippageProg
